#include <stdio.h>
unsigned long a(unsigned long n)
{
    if(n%2==0) n=n/2;
    else n=3*n+1;
    return n;
}

void main()
{
    unsigned long n;
    int i;
    while(scanf("%lu",&n)!=EOF){
        printf("Hailstone generated by %lu:\n",n);
        for(i=1;n!=1;++i){
            printf("%lu ",n);
            n=a(n);
        }
        printf("1\nNumber of hailstone generated:%d\n\n",i);
    }
}
